# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reading_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
